### ISSUE TITLE
Prerequisite question

### ISSUE THREAD

**Issue by ElYusubov** [hansenms/FhirDemo#2]
@hansenms thanks for putting this together!

My apologies, for a bit newbie question here. as i am trying complete the app registration to fulfill demo prerequisite:

1. An application registration for the FHIR API. 
Once i am able to register a new API web application on Azure, where i will use its credentials?

2. A client application registration for use with the demo web client (screen shot attached)
I created registration in AAD for this app, but not sure where to get the **aadClientSecret**.
![image](https://user-images.githubusercontent.com/29330538/54202251-fc052900-44a5-11e9-8657-f4c17ecadffc.png)

Does **aadClientId** refer to Application ID ? what about the **aadClientSecret** where i can get that value, as i looked at **Settings** -> **Properties** tab, but did not see it.

3. A service client application registration - does it need AAD Application registration id and secret?  should i follow step 2 for it?

Is there a complete instruction on how to set this demo environment from zero to end?
Or a quick video that might be very helpful?

**Comment by hansenms** [comment]
There is a script that does all these registrations for you. Please follow the code in there. 

1. Not sure I get that question.
2. The client secret is never display (except right when you create it). You can a add a new one. Again the script captures this for you.
3. The service client has an id (it is the app id) and yes, it needs a secret. 

Please use the script.

**Comment by ElYusubov** [comment]
I skipped doing provisioning manually, and used provided PS scripts. Thanks @hansenms !
