### ISSUE TITLE
Error to access client app

### ISSUE THREAD

**Issue by ElYusubov** [hansenms/FhirDemo#3]
Hi @hansenms 
I still have issues opening the client app, after a successful provisioning from provided template.
Following error on login shows up:

![image](https://user-images.githubusercontent.com/29330538/55102480-dd558380-509c-11e9-8767-c529513021c4.png)

![image](https://user-images.githubusercontent.com/29330538/55102558-070eaa80-509d-11e9-83d9-8d63bf048002.png)

Only thing that works is FHIR server capability statement. `{baseUrl}/metadata`

Any thought on why client app does not work (when deployed from button "Deploy to Azure")?

**Comment by ElYusubov** [comment]
@hansenms - probably, i found an issue in FHIR client AD configuration.
Is the following screen shows how a client website should be looking like?

![image](https://user-images.githubusercontent.com/29330538/55096057-957c2f80-508f-11e9-8c70-3830d3fc2b04.png)

**Comment by hansenms** [comment]
Yep, that looks about right.

**Comment by ElYusubov** [comment]
Cool, issue was in AAD authentication of the apps config!
It all started to work, once AAD details were reset ...

Thus, just make sure that all properties are set correct, including `Issuer Url`. 
Looks like a bug in an ARM template.

![image](https://user-images.githubusercontent.com/29330538/55102192-4092e600-509c-11e9-8f62-a29b40fee596.png)
